<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>This Source Code Form is subject to the terms of the MIT License. If a copy of the MIT license was not distributed with this file, You can obtain one at http://www.opensource.org/licenses/mit-license.php.</string>

	<key>name</key>
	<string>Mercury</string>

	<key>fileTypes</key>
	<array>
		<string>m</string>
	</array>
		
<!-- 	<key>firstLineMatch</key>
	<string>-[*]-( Mode:)? Go -[*]-</string> -->
	
	<!-- <key>foldingStartMarker</key>
	<string>(?x)
          /\*\*(?!\*)                           # opening C-style comment with 2 asterisks but no third later on
         |                                      # OR
          ^                                     # start of line...
           (?!                                  # ...which does NOT contain...
              [^{(]*?//                         #    ...a possible bunch of non-opening-braces, followed by a C++ comment
             |                                  #    OR
              [^{(]*?/\*(?!.*?\*/.*?[{(])       #    ...a possible bunch of non-opening-braces, followed by a C comment with no ending
           )
           .*?                                  # ...any characters (or none)...
           [{(]\s*                              # ...followed by an open brace and zero or more whitespace...
           (                                    # ...followed by...
            $                                   #    ...a dollar...
             |                                  #    OR
            //                                  #    ...a C++ comment...
             |                                  #    OR
            /\*(?!.*?\*/.*\S)                   #    ...a C comment, so long as no non-whitespace chars follow it..
           )
    </string>

	<key>foldingStopMarker</key>
	<string>(?&lt;!\*)\*\*/|^\s*[})]</string>
	 -->

	<key>keyEquivalent</key>
	<string>^~M</string>

	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\))\s*(:-)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.clause.bodybegin.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>[.^%]*(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.clause.bodyend.mercury</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.clause.body.mercury</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#controlandkeywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atom</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>meta.clause.body.mercury</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([a-zA-Z][a-zA-Z0-9_]*\()(?=.*:-.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.clause.headbegin.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))(?=\s*:-)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.clause.headend.mercury</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.clause.head.mercury</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#atom</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([a-z][a-zA-Z0-9_]*\()(?=.*--&gt;.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.dcg.headbegin.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))(?=\s*--&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.dcg.headend.mercury</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.dcg.head.mercury</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#atom</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\))\s*(--&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.dcg.bodybegin.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>[.^%]*(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.dcg.bodyend.mercury</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.dcg.body.mercury</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#controlandkeywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atom</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>meta.dcg.body.mercury</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>TODO match newlines</string>
			<key>match</key>
			<string>\s*[a-zA-Z][a-zA-Z0-9_]*\([^\.]*\)[\s^\n]*\.</string>
			<key>name</key>
			<string>entity.name.function.fact.mercury</string>
		</dict>
	</array>
	
	<key>repository</key>
	<dict>
		<key>atom</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;![a-zA-Z0-9_])[a-z][a-zA-Z0-9_]*(?!\s*\(|[a-zA-Z0-9_])</string>
					<key>name</key>
					<string>constant.other.atom.simple.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>'.*?'</string>
					<key>name</key>
					<string>constant.other.atom.quoted.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[\]</string>
					<key>name</key>
					<string>constant.other.atom.emptylist.mercury</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%.*</string>
					<key>name</key>
					<string>comment.line.percent-sign.mercury</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;![a-zA-Z]|/)\d+</string>
					<key>name</key>
					<string>constant.numeric.integer.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>".*?"</string>
					<key>name</key>
					<string>string.quoted.mercury</string>
				</dict>
			</array>
		</dict>
		<key>controlandkeywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(-&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.if.mercury</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.else.mercury</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.if.mercury</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#atom</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>meta.if.body.mercury</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>!</string>
					<key>name</key>
					<string>keyword.control.cut.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\s(is)\s)|=:=|==|=|\\\+|&gt;|&lt;|\+|\*|\-</string>
					<key>name</key>
					<string>keyword.operator.mercury</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;![a-zA-Z0-9_])[A-Z][a-zA-Z0-9_]*</string>
					<key>name</key>
					<string>variable.parameter.uppercase.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)_</string>
					<key>name</key>
					<string>variable.language.anonymous.mercury</string>
				</dict>
			</array>
		</dict>
	</dict>
	
	<key>scopeName</key>
	<string>source.mercury</string>
	
	<key>uuid</key>
	<string>df89928b-6612-475a-b414-f319d9b98664</string>

</dict>
</plist>
